### ISSUE TITLE
make the code more modular

### ISSUE THREAD

**Issue by AravindIM** [AravindIM/hades-logic-design-assignment#1]

**Comment by milanojs** [comment]
need to refactor ? or want functions shorter?

**Comment by RedGrinGrumbler** [comment]
Mind if I do this for Hacktoberfest?

**Comment by milanojs** [comment]
> Mind if I do this for Hacktoberfest?

we are hunting pr xD

**Comment by AravindIM** [comment]
@milanojs Ya, give it your best! Just make some functions and make it modular. Thanks.

**Comment by AravindIM** [comment]
@milanojs refactor it pls.
